name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Check gcloud version
      run: gcloud version

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy hello_world_function \
          --gen2 \
          --region=asia-east1 \
          --runtime=python312 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point=main
