name: Deploy to Cloud Functions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Deploy to Cloud Functions'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      with:
        name: 'hello_world_function'
        description: '測試'
        region: 'asia-east1'
        runtime: 'python312'
        cpu: '0.5'
        memory_mb: '128M'
        entry_point: 'main'
